# --------------------------------------------------------------------------------------- #
# Compiler Flag Configuration for Build Tools                                             #
#                                                                                         #
# This script sets compiler-specific flags based on detected compiler (GCC, Clang, MSVC)  #
# and CMake options prefixed with EYA_COMPILE_OPTION_. Each enabled option translates to  #
# appropriate compiler-specific flags for the target build configuration.                 #
# --------------------------------------------------------------------------------------- #

# Retrieve all variables in current CMake directory
get_property(CMAKE_OPTIONS DIRECTORY PROPERTY VARIABLES)
foreach (CMAKE_OPTION IN ITEMS ${CMAKE_OPTIONS})
    if (CMAKE_OPTION MATCHES "^EYA_COMPILE_OPTION_.*")
        # Helper function for safely adding compile flags
        function(eya_add_compile_option_if_missing OPTION_VALUE)
            if (NOT "${OPTION_VALUE}" IN_LIST EYA_TARGET_PRIVATE_COMPILE_OPTIONS)
                list(APPEND EYA_TARGET_PRIVATE_COMPILE_OPTIONS ${OPTION_VALUE})
                set(EYA_TARGET_PRIVATE_COMPILE_OPTIONS "${EYA_TARGET_PRIVATE_COMPILE_OPTIONS}" PARENT_SCOPE)
            endif()
        endfunction()

        function(eya_add_link_option_if_missing OPTION_VALUE)
            if (NOT "${OPTION_VALUE}" IN_LIST EYA_TARGET_PRIVATE_LINK_OPTIONS)
                list(APPEND EYA_TARGET_PRIVATE_LINK_OPTIONS ${OPTION_VALUE})
                set(EYA_TARGET_PRIVATE_LINK_OPTIONS "${EYA_TARGET_PRIVATE_LINK_OPTIONS}" PARENT_SCOPE)
            endif()
        endfunction()

        function(eya_add_link_library_if_missing OPTION_VALUE)
            if (NOT "${OPTION_VALUE}" IN_LIST EYA_TARGET_PRIVATE_LINK_LIBRARIES)
                list(APPEND EYA_TARGET_PRIVATE_LINK_LIBRARIES ${OPTION_VALUE})
                set(EYA_TARGET_PRIVATE_LINK_LIBRARIES "${EYA_TARGET_PRIVATE_LINK_LIBRARIES}" PARENT_SCOPE)
            endif()
        endfunction()        

        # Optimization Level Handling
        if (CMAKE_OPTION STREQUAL "EYA_COMPILE_OPTION_OPTIMIZATION")
            if (${CMAKE_OPTION} STREQUAL "ON")
                if (CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
                    eya_add_compile_option_if_missing(-O3)
                elseif (CMAKE_C_COMPILER_ID STREQUAL "MSVC")
                    eya_add_compile_option_if_missing(/O2)
                endif()
            else()
                if (CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
                    eya_add_compile_option_if_missing(-O0)
                elseif (CMAKE_C_COMPILER_ID STREQUAL "MSVC")
                    eya_add_compile_option_if_missing(/Od)
                endif()
            endif()
            continue()
        endif()

        # Debug Symbols Configuration
        if (CMAKE_OPTION STREQUAL "EYA_COMPILE_OPTION_DEBUG")
            if (${CMAKE_OPTION} STREQUAL "ON")
                if (CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
                    eya_add_compile_option_if_missing(-g)
                elseif (CMAKE_C_COMPILER_ID STREQUAL "MSVC")
                    eya_add_compile_option_if_missing(/Zi)
                endif()
            endif()
            continue()
        endif()

        # Instruction Set Optimizations
        if (CMAKE_OPTION STREQUAL "EYA_COMPILE_OPTION_SSE2")
            if (${CMAKE_OPTION} STREQUAL "ON")
                if (CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
                    eya_add_compile_option_if_missing(-msse2)
                elseif (CMAKE_C_COMPILER_ID STREQUAL "MSVC")
                    eya_add_compile_option_if_missing(/arch:SSE2)
                endif()
            endif()
            continue()
        endif()

        if (CMAKE_OPTION STREQUAL "EYA_COMPILE_OPTION_AVX2")
            if (${CMAKE_OPTION} STREQUAL "ON")
                if (CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
                    eya_add_compile_option_if_missing(-mavx2)
                elseif (CMAKE_C_COMPILER_ID STREQUAL "MSVC")
                    eya_add_compile_option_if_missing(/arch:AVX2)
                endif()
            endif()
            continue()
        endif()

        if (CMAKE_OPTION STREQUAL "EYA_COMPILE_OPTION_AVX512")
            if (${CMAKE_OPTION} STREQUAL "ON")
                if (CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
                    eya_add_compile_option_if_missing(-mavx512f)
                    eya_add_compile_option_if_missing(-mavx512bw)
                    eya_add_compile_option_if_missing(-mavx512vl)
                elseif (CMAKE_C_COMPILER_ID STREQUAL "MSVC")
                    eya_add_compile_option_if_missing(/arch:AVX512)
                endif()
            endif()
            continue()
        endif()

        # Link-Time Optimization
        if (CMAKE_OPTION STREQUAL "EYA_COMPILE_OPTION_LTO")
            if (${CMAKE_OPTION} STREQUAL "ON")
                if (CMAKE_C_COMPILER_ID STREQUAL "GNU")
                    eya_add_compile_option_if_missing(-flto)
                elseif (CMAKE_C_COMPILER_ID STREQUAL "Clang")
                    find_program(LLD_LINKER lld)
                    if (LLD_LINKER)
                        eya_add_compile_option_if_missing(-flto)
                        eya_add_link_option_if_missing(-fuse-ld=lld)
                    else()
                        message(WARNING "LLD linker not found - disabling LTO for Clang")
                    endif()
                elseif (CMAKE_C_COMPILER_ID STREQUAL "MSVC")
                    eya_add_compile_option_if_missing(/GL)
                    eya_add_link_option_if_missing(/LTCG)
                endif()
            endif()
            continue()
        endif()

        # Loop Unrolling
        if (CMAKE_OPTION STREQUAL "EYA_COMPILE_OPTION_UNROLL_LOOPS")
            if (${CMAKE_OPTION} STREQUAL "ON")
                if (CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
                    eya_add_compile_option_if_missing(-funroll-loops)
                endif()
            endif()
            continue()
        endif()

        # Security Features
        if (CMAKE_OPTION STREQUAL "EYA_COMPILE_OPTION_NO_STACK_PROTECTOR")
            if (${CMAKE_OPTION} STREQUAL "ON")
                if (CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
                    eya_add_compile_option_if_missing(-fno-stack-protector)
                elseif (CMAKE_C_COMPILER_ID STREQUAL "MSVC")
                    eya_add_compile_option_if_missing(/GS-)
                endif()
            endif()
            continue()
        endif()

        # Position Independent Code
        if (CMAKE_OPTION STREQUAL "EYA_COMPILE_OPTION_PIC")
            if (${CMAKE_OPTION} STREQUAL "ON")
                if (${EYA_LIBRARY_OPTION_STATIC_BUILD})
                    message(FATAL_ERROR "PIC incompatible with static builds")
                endif()
                if (CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
                    eya_add_compile_option_if_missing(-fPIC)
                endif()
            endif()
            continue()
        endif()

        # Language Features
        if (CMAKE_OPTION STREQUAL "EYA_COMPILE_OPTION_NO_RTTI")
            if (${CMAKE_OPTION} STREQUAL "ON")
                if (CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
                    eya_add_compile_option_if_missing(-fno-rtti)
                elseif (CMAKE_C_COMPILER_ID STREQUAL "MSVC")
                    eya_add_compile_option_if_missing(/GR-)
                endif()
            endif()
            continue()
        endif()

        if (CMAKE_OPTION STREQUAL "EYA_COMPILE_OPTION_NO_EXCEPTIONS")
            if (${CMAKE_OPTION} STREQUAL "ON")
                if (CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
                    eya_add_compile_option_if_missing(-fno-exceptions)
                elseif (CMAKE_C_COMPILER_ID STREQUAL "MSVC")
                    eya_add_compile_option_if_missing(/EHsc-)
                endif()
            endif()
            continue()
        endif()

        if (CMAKE_OPTION STREQUAL "EYA_COMPILE_OPTION_THREAD_SAFETY")
            if (${CMAKE_OPTION} STREQUAL "ON")
                if (CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
                    eya_add_compile_option_if_missing(-pthread)
                endif()
            endif()
            continue()
        endif()

        if (CMAKE_OPTION STREQUAL "EYA_COMPILE_OPTION_FAST_MATH")
            if (${CMAKE_OPTION} STREQUAL "ON")
                if (CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
                    eya_add_compile_option_if_missing(-ffast-math)
                    eya_add_compile_option_if_missing(-fno-math-errno)
                    eya_add_compile_option_if_missing(-funsafe-math-optimizations)
                elseif (CMAKE_C_COMPILER_ID STREQUAL "MSVC")
                    eya_add_compile_option_if_missing(/fp:fast)
                endif()
            endif()
            continue()
        endif()

        if (CMAKE_OPTION STREQUAL "EYA_COMPILE_OPTION_NATIVE_TUNE")
            if (${CMAKE_OPTION} STREQUAL "ON")
                if (CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
                    eya_add_compile_option_if_missing(-march=native)
                    eya_add_compile_option_if_missing(-mtune=native)
                endif()
            endif()
            continue()
        endif()

        # Branch Prediction Optimizations
        if (CMAKE_OPTION STREQUAL "EYA_COMPILE_OPTION_BRANCH_PREDICTION")
            if (${CMAKE_OPTION} STREQUAL "ON")
                if (CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
                    find_library(GCOV_LIBRARY gcov)
                    if(GCOV_LIBRARY)
                        eya_add_compile_option_if_missing(-fprofile-arcs)
                        eya_add_compile_option_if_missing(-fpredictive-commoning)
                        find_library(GCONV_LIBRARY gconv)
                        if(GCONV_LIBRARY)
                            eya_add_link_library_if_missing(gconv)
                        else()
                            message(WARNING "Library gconv not found - branch prediction optimizations may be limited")
                        endif()
                    endif()
                elseif (CMAKE_C_COMPILER_ID STREQUAL "MSVC")
                    eya_add_compile_option_if_missing(/Qspectre)
                endif()
            endif()
            continue()
        endif()

        # Memory Optimizations
        if (CMAKE_OPTION STREQUAL "EYA_COMPILE_OPTION_MEMORY_OPT")
            if (${CMAKE_OPTION} STREQUAL "ON")
                if (CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
                    eya_add_compile_option_if_missing(-fprefetch-loop-arrays)
                elseif (CMAKE_C_COMPILER_ID STREQUAL "MSVC")
                    eya_add_compile_option_if_missing(/Oi)
                endif()
            endif()
            continue()
        endif()

        # Parallelization
        if (CMAKE_OPTION STREQUAL "EYA_COMPILE_OPTION_PARALLEL")
            if (${CMAKE_OPTION} STREQUAL "ON")
                if (CMAKE_C_COMPILER_ID STREQUAL "GNU")
                    eya_add_compile_option_if_missing(-floop-parallelize-all)
                    eya_add_compile_option_if_missing(-ftree-parallelize-loops=4)
                elseif (CMAKE_C_COMPILER_ID STREQUAL "Clang")
                    eya_add_compile_option_if_missing(-mllvm -polly)
                    eya_add_compile_option_if_missing(-mllvm -polly-parallel)
                    eya_add_compile_option_if_missing(-mllvm -polly-num-threads=4)
                elseif (CMAKE_C_COMPILER_ID STREQUAL "MSVC")
                    eya_add_compile_option_if_missing(/Qpar)
                endif()
            endif()
            continue()
        endif()

        # Visibility Hidden (reduces binary size)
        if (CMAKE_OPTION STREQUAL "EYA_COMPILE_OPTION_VISIBILITY_HIDDEN")
            if (${CMAKE_OPTION} STREQUAL "ON")
                if (CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
                    eya_add_compile_option_if_missing(-fvisibility=hidden)
                endif()
            endif()
            continue()
        endif()

        # Function Sections (improves dead code elimination)
        if (CMAKE_OPTION STREQUAL "EYA_COMPILE_OPTION_FUNCTION_SECTIONS")
            if (${CMAKE_OPTION} STREQUAL "ON")
                if (CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
                    eya_add_compile_option_if_missing(-ffunction-sections)
                    eya_add_compile_option_if_missing(-fdata-sections)
                    eya_add_link_option_if_missing(-Wl,--gc-sections)
                elseif (CMAKE_C_COMPILER_ID STREQUAL "MSVC")
                    eya_add_link_option_if_missing(/OPT:REF)
                endif()
            endif()
            continue()
        endif()
    endif()
endforeach()

# Display enabled compilation options
message(STATUS "Active compilation features:")
foreach (CMAKE_OPTION IN ITEMS ${CMAKE_OPTIONS})
    if (CMAKE_OPTION MATCHES "^EYA_COMPILE_OPTION_.*" AND ${CMAKE_OPTION} STREQUAL "ON")
        message(STATUS "  • ${CMAKE_OPTION}")
        list(APPEND EYA_TARGET_PUBLIC_COMPILE_DEFINITIONS ${CMAKE_OPTION})
    endif()
endforeach()